name: Run Python Unittests

on:
  push:
    branches:
      - dev
      - master

jobs:
  test:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run unittests
        run: |
          mkdir -p logs
          cd tests
          python run_parallel_tests.py --verbose 2>&1 | tee ../logs/test-${{ matrix.python-version }}.log

  test_full:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run unittests
        run: |
          mkdir -p logs
          cd tests
          python run_parallel_tests.py --verbose 2>&1 | tee ../logs/test-${{ matrix.python-version }}.log
